# .github/workflows/workflow.yml

name: Francinette Tests

on:
  workflow_dispatch:

jobs:
  run_francinette:
    name: Run Francinette Tests
    runs-on: ubuntu-latest

    env:
      TERM: xterm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential python3 python3-pip

      - name: Install Python dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install gitpython halo toml

      - name: Clone francinette
        run: |
          git clone https://github.com/xicodomingues/francinette.git francinette

      - name: Run francinette tests
        run: |
          python3 francinette/main.py