# .github/workflows/workflow.yml

name: Francinette Tests

on:
  workflow_dispatch:

jobs:
  run_francinette:
    name: Run Francinette Tests
    runs-on: ubuntu-latest

    # TERM değişkeni tput ile renkli çıktı için gerekiyor
    env:
      TERM: xterm

    steps:
      # 1. Repoyu çek
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Gerekli sistem paketlerini yükle
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential python3 python3-pip

      # 3. Python kütüphanelerini yükle (gitpython, halo gerekiyor)
      - name: Install Python dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install gitpython halo

      # 4. Francinette deposunu klonla
      - name: Clone francinette
        run: |
          git clone https://github.com/xicodomingues/francinette.git francinette

      # 5. Francinette ile testleri çalıştır
      #    Bu komut, repoda hangi 42 projesi (örneğin libft) varsa otomatik algılar ve testleri yapar.
      - name: Run francinette tests
        run: |
          python3 francinette/main.py